export const drink1 = {
  idDrink: '15006',
  strDrink: 'Turkeyball',
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: 'Shot',
  strIBA: null,
  strAlcoholic: 'Alcoholic',
  strGlass: 'Shot glass',
  strInstructions: 'Shake with ice and strain into a shot glass.',
  strInstructionsES: null,
  strInstructionsDE: 'Mit Eis schütteln und in ein Schnapsglas abseihen.',
  strInstructionsFR: null,
  strInstructionsIT: 'Shakerare con ghiaccio e filtra in un bicchiere da shot',
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rxurpr1441554292.jpg',
  strIngredient1: 'Wild Turkey',
  strIngredient2: 'Amaretto',
  strIngredient3: 'Pineapple juice',
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '1 oz ',
  strMeasure2: '3/4 oz ',
  strMeasure3: '1 splash ',
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: 'No',
  dateModified: '2015-09-06 16:44:53',
};

export const drink2 = {
  idDrink: '12870',
  strDrink: 'Artillery Punch',
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: 'Punch / Party Drink',
  strIBA: null,
  strAlcoholic: 'Alcoholic',
  strGlass: 'Punch bowl',
  strInstructions: 'Combine all the ingredients in a large punch bowl with a block of ic'
  + 'e. If found too dry, sugar syrup may be added. Decorate with twists of lemon peel.',
  strInstructionsES: null,
  strInstructionsDE: 'Alle Zutaten in einer großen Bowle mit einem Eisblock vermengen. '
  + 'Wenn es zu trocken ist, kann Zuckersirup hinzugefügt werden. Mit Zitronenschalen '
  + 'garnieren.',
  strInstructionsFR: null,
  strInstructionsIT: 'Unisci tutti gli ingredienti in una grande ciotola da punch con'
  + ' tanto ghiaccio.\r\nSe risulta troppo secco, puoi aggiungere un po’ di sciroppo '
  + 'di zucchero.\r\nDecora con dei limoni.',
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/9a4vqb1493067692.jpg',
  strIngredient1: 'Tea',
  strIngredient2: 'Rye whiskey',
  strIngredient3: 'Red wine',
  strIngredient4: 'Rum',
  strIngredient5: 'Brandy',
  strIngredient6: 'Benedictine',
  strIngredient7: 'Orange juice',
  strIngredient8: 'Lemon juice',
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '1 quart black ',
  strMeasure2: '1 quart ',
  strMeasure3: '1 fifth ',
  strMeasure4: '1 pint Jamaican ',
  strMeasure5: '1/2 pint ',
  strMeasure6: '1 1/2 oz ',
  strMeasure7: '1 pint ',
  strMeasure8: '1/2 pint ',
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: 'No',
  dateModified: '2017-04-24 22:01:32',
};

export const drink3 = {
  idDrink: '14053',
  strDrink: 'Mother\'s Milk',
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: 'Shot',
  strIBA: null,
  strAlcoholic: 'Alcoholic',
  strGlass: 'Shot glass',
  strInstructions: 'Shake over ice, strain. Serves two.',
  strInstructionsES: null,
  strInstructionsDE: 'Über Eis schütteln, abseihen. Für zwei Personen.',
  strInstructionsFR: null,
  strInstructionsIT: 'Shakerare sul ghiaccio, filtrare.\r\nPer due persone.',
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/7stuuh1504885399.jpg',
  strIngredient1: 'Goldschlager',
  strIngredient2: 'Butterscotch schnapps',
  strIngredient3: 'Milk',
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '1 oz ',
  strMeasure2: '1 oz ',
  strMeasure3: '1 oz ',
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: 'No',
  dateModified: '2017-09-08 16:43:19',
};

export const drinks = {
  drink1, drink2, drink3,
};
