export const mealsIngredients = {
  meals: [
    {
      idIngredient: '1',
      strIngredient: 'Chicken',
      strDescription: 'description1',
      strType: null,
    },
    {
      idIngredient: '2',
      strIngredient: 'Salmon',
      strDescription: 'description2',
      strType: null,
    },
    {
      idIngredient: '3',
      strIngredient: 'Beef',
      strDescription: 'description3',
      strType: null,
    },
    {
      idIngredient: '4',
      strIngredient: 'Pork',
      strDescription: 'description4',
      strType: null,
    },
    {
      idIngredient: '5',
      strIngredient: 'Avocado',
      strDescription: 'description5',
      strType: null,
    },
    {
      idIngredient: '9',
      strIngredient: 'Apple Cider Vinegar',
      strDescription: 'description9',
      strType: null,
    },
    {
      idIngredient: '10',
      strIngredient: 'Asparagus',
      strDescription: 'description10',
      strType: null,
    },
    {
      idIngredient: '11',
      strIngredient: 'Aubergine',
      strDescription: 'description11',
      strType: null,
    },
    {
      idIngredient: '13',
      strIngredient: 'Baby Plum Tomatoes',
      strDescription: 'description13',
      strType: null,
    },
    {
      idIngredient: '14',
      strIngredient: 'Bacon',
      strDescription: 'description14',
      strType: null,
    },
    {
      idIngredient: '15',
      strIngredient: 'Baking Powder',
      strDescription: 'description15',
      strType: null,
    },
    {
      idIngredient: '16',
      strIngredient: 'Balsamic Vinegar',
      strDescription: 'description16',
      strType: null,
    },
    {
      idIngredient: '17',
      strIngredient: 'Basil',
      strDescription: 'description17',
      strType: null,
    },
    {
      idIngredient: '18',
      strIngredient: 'Basil Leaves',
      strDescription: 'description18',
      strType: null,
    },
    {
      idIngredient: '19',
      strIngredient: 'Basmati Rice',
      strDescription: 'description19',
      strType: null,
    },
  ],
};

export const mealsIngredientsImgs = {
  Chicken: 'https://www.themealdb.com/images/ingredients/Chicken.png',
  Salmon: 'https://www.themealdb.com/images/ingredients/Salmon.png',
  Beef: 'https://www.themealdb.com/images/ingredients/Beef.png',
  Pork: 'https://www.themealdb.com/images/ingredients/Pork.png',
  Avocado: 'https://www.themealdb.com/images/ingredients/Avocado.png',
  'Apple Cider Vinegar': 'https://www.themealdb.com/images/ingredients/Apple Cider Vinegar.png',
  Asparagus: 'https://www.themealdb.com/images/ingredients/Asparagus.png',
  Aubergine: 'https://www.themealdb.com/images/ingredients/Aubergine.png',
  'Baby Plum Tomatoes': 'https://www.themealdb.com/images/ingredients/Baby Plum Tomatoes.png',
  Bacon: 'https://www.themealdb.com/images/ingredients/Bacon.png',
  'Baking Powder': 'https://www.themealdb.com/images/ingredients/Baking Powder.png',
  'Balsamic Vinegar': 'https://www.themealdb.com/images/ingredients/Baking Powder.png',
  Basil: 'https://www.themealdb.com/images/ingredients/Basil.png',
  'Basil Leaves': 'https://www.themealdb.com/images/ingredients/Basil Leaves.png',
  'Basmati Rice': 'https://www.themealdb.com/images/ingredients/Basmati Rice.png',
};

export const drinksIngredients = {
  drinks: [
    { strIngredient1: 'Light rum' },
    { strIngredient1: 'Applejack' },
    { strIngredient1: 'Gin' },
    { strIngredient1: 'Dark rum' },
    { strIngredient1: 'Sweet Vermouth' },
    { strIngredient1: 'Strawberry schnapps' },
    { strIngredient1: 'Scotch' },
    { strIngredient1: 'Apricot brandy' },
    { strIngredient1: 'Triple sec' },
    { strIngredient1: 'Southern Comfort' },
    { strIngredient1: 'Orange bitters' },
    { strIngredient1: 'Brandy' },
    { strIngredient1: 'Lemon vodka' },
    { strIngredient1: 'Blended whiskey' },
    { strIngredient1: 'Dry Vermouth' },
  ],
};

export const drinksIngredientsImgs = {
  'Light rum': 'https://thecocktaildb.com/images/ingredients/Light rum.png',
  Applejack: 'https://thecocktaildb.com/images/ingredients/Applejack.png',
  Gin: 'https://thecocktaildb.com/images/ingredients/Gin.png',
  'Dark rum': 'https://thecocktaildb.com/images/ingredients/Dark rum.png',
  'Sweet Vermouth': 'https://thecocktaildb.com/images/ingredients/Sweet Vermouth.png',
  'Strawberry schnapps': 'https://thecocktaildb.com/images/ingredients/Strawberry schnapps.png',
  Scotch: 'https://thecocktaildb.com/images/ingredients/Scotch.png',
  'Apricot brandy': 'https://thecocktaildb.com/images/ingredients/Apricot brandy.png',
  'Triple sec': 'https://thecocktaildb.com/images/ingredients/Triple sec.png',
  'Southern Comfort': 'https://thecocktaildb.com/images/ingredients/Southern Comfort.png',
  'Orange bitters': 'https://thecocktaildb.com/images/ingredients/Orange bitters.png',
  Brandy: 'https://thecocktaildb.com/images/ingredients/Brandy.png',
  'Lemon vodka': 'https://thecocktaildb.com/images/ingredients/Lemon vodka.png',
  'Blended whiskey': 'https://thecocktaildb.com/images/ingredients/Blended whiskey.png',
  'Dry Vermouth': 'https://thecocktaildb.com/images/ingredients/Dry Vermouth.png',
};
